# Generated by Django 5.2.3 on 2025-06-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='product',
        ),
    ]
