# Generated by Django 5.2.3 on 2025-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_name_inventoryitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('box', 'Box'), ('case', 'Case'), ('pallet', 'Pallet'), ('kg', 'Kilogram'), ('gram', 'Gram'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('meter', 'Meter'), ('cm', 'Centimeter'), ('pack', 'Pack'), ('set', 'Set'), ('unit', 'Unit'), ('dozen', 'Dozen')], default='piece', max_length=20),
        ),
    ]
