# Generated by Django 5.2.3 on 2025-08-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_unit'),
        ('products', '0009_remove_product_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('product', 'unit')},
        ),
    ]
