# Generated by Django 5.2.3 on 2025-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
