# Generated by Django 5.2.3 on 2025-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_total_price_orderitem_total_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for this order', max_length=255, null=True),
        ),
    ]
