# Generated by Django 5.2.3 on 2025-08-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_unique_together'),
        ('orders', '0011_order_customer_address_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
    ]
