# Generated by Django 5.2.3 on 2025-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('ltr', 'Liters'), ('box', 'Box'), ('mtr', 'Meters'), ('pkt', 'Packets')], default='pcs', max_length=10),
        ),
    ]
