# Generated by Django 5.2.3 on 2025-07-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cost_price_product_selling_price_ledgerentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productledger',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
        migrations.DeleteModel(
            name='ProductLedger',
        ),
    ]
