# Generated by Django 5.2.3 on 2025-07-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productledger_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_type',
        ),
    ]
