# Generated by Django 5.2.3 on 2025-07-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_cost_price_product_selling_price_ledgerentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
