# Generated by Django 5.2.3 on 2025-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorderitem_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
